/*
 * Main_Frame_Reader.java
 *
 * Created on __DATE__, __TIME__
 */

package com.test;

import javax.swing.JFrame;

/**
 *
 * @author  __USER__
 */
public class Main_Frame_Reader extends javax.swing.JFrame {

	/** Creates new form Main_Frame_Reader */
	public Main_Frame_Reader() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();
		jMenu5 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u8bfb\u8005\u4e2d\u5fc3");

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"./picture/backImg.jpg")); // NOI18N

		jMenu1.setText("\u4e2a\u4eba\u4e2d\u5fc3");

		jMenuItem1.setText("\u67e5\u770b\u4fe1\u606f");
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("\u4fee\u6539\u4fe1\u606f");
		jMenu1.add(jMenuItem2);

		jMenuItem3.setText("\u5237\u65b0\u4fe1\u606f");
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u501f\u9605\u4e2d\u5fc3");

		jMenuItem4.setText("\u67e5\u4e66");
		jMenu2.add(jMenuItem4);

		jMenuItem6.setText("\u501f\u4e66");
		jMenu2.add(jMenuItem6);

		jMenuItem7.setText("\u8fd8\u4e66");
		jMenu2.add(jMenuItem7);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("\u5728\u7ebf\u9605\u8bfb");
		jMenuBar1.add(jMenu3);

		jMenu4.setText("\u8054\u7cfb\u6211\u4eec");
		jMenuBar1.add(jMenu4);

		jMenu5.setText("\u610f\u89c1\u53cd\u9988");
		jMenuBar1.add(jMenu5);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1));

		pack();
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//Ç§Íò²»ÄÜÉ¾
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main_Frame_Reader().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	// End of variables declaration//GEN-END:variables

}