/*
 * Main_Frame_Admin.java
 *
 * Created on __DATE__, __TIME__
 */

package com.test;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author  __USER__
 */
public class Main_Frame_Admin extends javax.swing.JFrame {

	/** Creates new form Main_Frame_Admin */
	public Main_Frame_Admin() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();
		jMenuItem10 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem11 = new javax.swing.JMenuItem();
		jMenuItem12 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7ba1\u7406\u5458\u4e2d\u5fc3");

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"./picture/backImg.jpg")); // NOI18N

		jMenu1.setText("\u56fe\u4e66\u7ba1\u7406");

		jMenuItem4.setText("\u67e5\u8be2\u56fe\u4e66");
		jMenu1.add(jMenuItem4);

		jMenuItem5.setText("\u65b0\u589e\u56fe\u4e66");
		jMenu1.add(jMenuItem5);

		jMenuItem6.setText("\u4fee\u6539\u56fe\u4e66");
		jMenu1.add(jMenuItem6);

		jMenuItem7.setText("\u5220\u9664\u56fe\u4e66");
		jMenu1.add(jMenuItem7);

		jMenuItem8.setText("\u5237\u65b0\u56fe\u4e66");
		jMenu1.add(jMenuItem8);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u7528\u6237\u7ba1\u7406");

		jMenuItem1.setText("\u67e5\u8be2\u7528\u6237");
		jMenu2.add(jMenuItem1);

		jMenuItem2.setText("\u65b0\u589e\u7528\u6237");
		jMenu2.add(jMenuItem2);

		jMenuItem3.setText("\u4fee\u6539\u7528\u6237");
		jMenu2.add(jMenuItem3);

		jMenuItem9.setText("\u5220\u9664\u7528\u6237");
		jMenu2.add(jMenuItem9);

		jMenuItem10.setText("\u5237\u65b0\u7528\u6237");
		jMenu2.add(jMenuItem10);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("\u501f\u9605\u7ba1\u7406");

		jMenuItem11.setText("\u501f\u4e66\u7684\u4eba");
		jMenu3.add(jMenuItem11);

		jMenuItem12.setText("\u88ab\u501f\u7684\u4e66");
		jMenu3.add(jMenuItem12);

		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1).addComponent(jLabel2));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1).addComponent(jLabel2));

		pack();
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//Ç§Íò²»ÄÜÉ¾
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main_Frame_Admin().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem10;
	private javax.swing.JMenuItem jMenuItem11;
	private javax.swing.JMenuItem jMenuItem12;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	// End of variables declaration//GEN-END:variables

}